services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: finance
    ports: ["5432:5432"]
    volumes: [db_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d finance"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  api:
    build: ./api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes: ["./api:/app"]
    restart: unless-stopped
  
  web:
    build: ./web
    env_file: .env
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    depends_on: [api]
    ports: ["3000:3000"]
    volumes: ["./web:/app"]
    restart: unless-stopped

volumes:
  db_data:
  driver: local